### ISSUE TITLE
Passage rates by genre

### ISSUE THREAD

**Issue by kgoodman3** [aamiller/Info201GroupProj#5]
After linking IMBD data to our FiveThirtyEight data I will evaluate the correlation between passage rates of the bechdel test and the genre of movie. I will get averages of passage rates by genre and plot the information to see if I can find a correlation between the two. I also hope to look at these trends over time and see if the correlation is consistent over time. This will give us a better understanding of what types of movies feature women, with names, that talk to each other about something other than a man.

**Comment by aamiller** [comment]
Closed by Adele. Created genre tab with bar graph.
